pipeline{
    agent any
  
    stages{
        stage("Install dependencies"){
            steps{
                load("helper/test.groovy").echoHelloWorld()
            }
            
        }
        
    }
    
}