pipeline{
    agent any
  
    stages{
        stage("Install dependencies"){
            steps{
                script {
                    load("helper/test.groovy").echoHelloWorld()
                }
            }
            
        }
        
    }
    
}