pipeline{
    agent any
  
    stages{
        stage("Install dependencies"){
            steps{
                script {
                    echo "HI"
                    // load("ci/helper/test.groovy").echoHelloWorld()
                }
            }
            
        }
        
    }
    
}